name: kdecole_api
description: An unofficial api for kdecole and Kosmos suite
version: 1.0.0
homepage: https://github.com/EduWireApps/kdecole-api-dart
# Maintained by Freezman31 <https://github.com/Freezman31>

environment:
  sdk: '>=2.15.0 <3.0.0'


dev_dependencies:
  lints: ^2.0.1
  test: ^1.16.0

dependencies:
  http: ^0.13.5
  html_unescape: ^2.0.0
  html: ^0.15.1